# Run tInstall on Ubuntu against python versions 3.11, 3.10 and 3.9

name: Test R2024a

on:
  push:
    branches:
      - R2024a

  pull_request:
    branches:
      - R2024a

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-python-engine:
    strategy:
      matrix:
        python: ["3.11", "3.10", "3.9"]

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3.1.3
        with:
           python-version: ${{ matrix.python }}

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
           release: R2024a

      - uses: actions/checkout@v3

      - name: Run tests
        uses: matlab-actions/run-tests@v1
