# Run tInstall on Ubuntu against python versions 3.12, 3.11, 3.10 and 3.9

name: Test R2025a

on:
  push:
    branches:
      - R2025a

  pull_request:
    branches:
      - R2025a

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-python-engine:
    strategy:
      matrix:
        python: ["3.12", "3.11", "3.10", "3.9"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
           python-version: ${{ matrix.python }}

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.5.0
        with:
           release: R2025a

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run tests
        uses: matlab-actions/run-tests@v2.1.1
