# Run tInstall in R2021a on Ubuntu against Python 3.8

name: Test R2021a

on:
  push:
    branches:
      - R2021a

  pull_request:
    branches:
      - R2021a

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-python-engine:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3.1.3
        with:
           python-version: 3.8

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
           release: R2021a

      - uses: actions/checkout@v3

      - name: Run tests
        uses: matlab-actions/run-tests@v1
